[package]
name = "fiox"
version = "0.1.0"
edition = "2024"
[workspace.metadata.clippy]
deny-warnings = true
[dependencies]
csv = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
toml = "0.8"
colored = "3"
